name: Build
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
      - uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: gradle build
      - uses: actions/upload-artifact@v3
        with:
          path: ['build/libs', 'dummy/build/libs']